# Generated by Django 4.1.3 on 2022-11-18 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_remove_measurement_sensor_id_sensor_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='measurement',
        ),
        migrations.AddField(
            model_name='measurement',
            name='measurement',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='measurement.sensor'),
            preserve_default=False,
        ),
    ]
